name: Build and Publish to Docker Hub

on:
    push:
        branches: [main]
        paths-ignore:
            - "**/README.md"
            - "**/LICENSE"
            - "**/.editorconfig"
            - "**/.gitignore"
            - ".vscode/*"
    pull_request:
        branches: [main]
        paths-ignore:
            - "**/README.md"
            - "**/LICENSE"
            - "**/.editorconfig"
            - "**/.gitignore"
            - ".vscode/*"

jobs:
    build_and_publish:
        name: Build and Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set Up Docker Buildx
              uses: docker/setup-buildx-action@v2
              id: buildx

            - name: Avaliable platforms
              run: echo ${{ steps.buildx.outputs.platforms }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v3
              with:
                  platforms: "linux/amd64, linux/arm64"
                  context: .
                  push: true
                  tags: "lpsouza/cloudflared:latest"
